### ISSUE TITLE
Mettre le Todo dans les issues

### ISSUE THREAD

**Issue by Zephyrin** [Zephyrin/BraKoLu#10]
Mettre la fin du todo en plus détaillé dans les issues github. Je n'ai pas tout compris du reste des TODOs. En plus, on pourra échanger et suivre les évolutions des différentes évolutions et bugs, les commenter et ainsi savoir ou l'on va.

**Comment by Zephyrin** [comment]
J'ai push des modifications ;)

**Comment by brakolu** [comment]
Fait. On conserve le TODO pour l'instant comme librairie de bug pas assez analysés.
