### ISSUE TITLE
Page ingrédient : Problème affichage chip selector

### ISSUE THREAD

**Issue by brakolu** [Zephyrin/BraKoLu#13]
A l'ouverture de cette page, afficher les Céréales (ou encore mieux afficher ce qui était affiché la dernière fois que l'on a quitté cette page)

Faire en sorte que l'on puisse afficher plusieurs types d'ingrédients en même par de multiple sélections de chip

**Comment by Zephyrin** [comment]
On peut déjà afficher plusieurs types d'ingrédients normalement. Si ce n'est pas le cas, il faut ouvrir un ticket de type bug.

**Comment by Zephyrin** [comment]
Réaliser avec le commit d'aujourd'hui que je n'arrive pas à linker.
