### ISSUE TITLE
Proposition charte graphique

### ISSUE THREAD

**Issue by brakolu** [Zephyrin/BraKoLu#16]
Déterminer 2 palettes de couleurs :
      Mode clair  -> https://colorhunt.co/palette/206818
      Mode sombre  -> https://colorhunt.co/palette/179373

Voir dossier ressources pour la bannière + favicon

**Comment by Zephyrin** [comment]
Je viens de trouver cette librarie d'icone qui pourrait-être bien sympa:
https://dev.materialdesignicons.com/getting-started/angular
https://cdn.materialdesignicons.com/5.4.55/
À voir ce que tu en penses.

**Comment by Zephyrin** [comment]
As tu l'icone favicon-Black en svg pure ? Car si je ne me trompe pas, c'est un png inclus dans un svg, non ?

**Comment by brakolu** [comment]
Thème clair généré grâce à : http://mcg.mbitson.com/#!?background=%23ffeadb&foreground=%23637373&primary=%23679b9b&accent=%23ff9a76&themename=brightbratool



/* For use in _color-definitions.scss */
$palette-background:
rgb(255, 243, 239)
rgb(255, 225, 214)
rgb(255, 205, 187)
rgb(255, 184, 159)
rgb(255, 169, 139)
rgb(255, 154, 118)
rgb(255, 146, 110)
rgb(255, 136, 99)
rgb(255, 126, 89)
rgb(255, 108, 70)
rgb(255, 255, 255)
rgb(255, 255, 255)
rgb(255, 241, 237)
rgb(255, 220, 212)
;

$palette-background-50: nth($palette-background, 1);
$palette-background-100: nth($palette-background, 2);
$palette-background-200: nth($palette-background, 3);
$palette-background-300: nth($palette-background, 4);
$palette-background-400: nth($palette-background, 5);
$palette-background-500: nth($palette-background, 6);
$palette-background-600: nth($palette-background, 7);
$palette-background-700: nth($palette-background, 8);
$palette-background-800: nth($palette-background, 9);
$palette-background-900: nth($palette-background, 10);
$palette-background-A100: nth($palette-background, 11);
$palette-background-A200: nth($palette-background, 12);
$palette-background-A400: nth($palette-background, 13);
$palette-background-A700: nth($palette-background, 14);


$palette-foreground:
rgb(236, 238, 238)
rgb(208, 213, 213)
rgb(177, 185, 185)
rgb(146, 157, 157)
rgb(122, 136, 136)
rgb(99, 115, 115)
rgb(91, 107, 107)
rgb(81, 96, 96)
rgb(71, 86, 86)
rgb(53, 67, 67)
rgb(155, 252, 252)
rgb(105, 251, 251)
rgb(50, 255, 255)
rgb(25, 255, 255)
;

$palette-foreground-50: nth($palette-foreground, 1);
$palette-foreground-100: nth($palette-foreground, 2);
$palette-foreground-200: nth($palette-foreground, 3);
$palette-foreground-300: nth($palette-foreground, 4);
$palette-foreground-400: nth($palette-foreground, 5);
$palette-foreground-500: nth($palette-foreground, 6);
$palette-foreground-600: nth($palette-foreground, 7);
$palette-foreground-700: nth($palette-foreground, 8);
$palette-foreground-800: nth($palette-foreground, 9);
$palette-foreground-900: nth($palette-foreground, 10);
$palette-foreground-A100: nth($palette-foreground, 11);
$palette-foreground-A200: nth($palette-foreground, 12);
$palette-foreground-A400: nth($palette-foreground, 13);
$palette-foreground-A700: nth($palette-foreground, 14);


$palette-primary:
rgb(237, 243, 243)
rgb(209, 225, 225)
rgb(179, 205, 205)
rgb(149, 185, 185)
rgb(126, 170, 170)
rgb(103, 155, 155)
rgb(95, 147, 147)
rgb(84, 137, 137)
rgb(74, 127, 127)
rgb(57, 109, 109)
rgb(191, 255, 255)
rgb(140, 255, 255)
rgb(89, 255, 255)
rgb(64, 255, 255)
;

$palette-primary-50: nth($palette-primary, 1);
$palette-primary-100: nth($palette-primary, 2);
$palette-primary-200: nth($palette-primary, 3);
$palette-primary-300: nth($palette-primary, 4);
$palette-primary-400: nth($palette-primary, 5);
$palette-primary-500: nth($palette-primary, 6);
$palette-primary-600: nth($palette-primary, 7);
$palette-primary-700: nth($palette-primary, 8);
$palette-primary-800: nth($palette-primary, 9);
$palette-primary-900: nth($palette-primary, 10);
$palette-primary-A100: nth($palette-primary, 11);
$palette-primary-A200: nth($palette-primary, 12);
$palette-primary-A400: nth($palette-primary, 13);
$palette-primary-A700: nth($palette-primary, 14);


$palette-accent:
rgb(255, 243, 239)
rgb(255, 225, 214)
rgb(255, 205, 187)
rgb(255, 184, 159)
rgb(255, 169, 139)
rgb(255, 154, 118)
rgb(255, 146, 110)
rgb(255, 136, 99)
rgb(255, 126, 89)
rgb(255, 108, 70)
rgb(255, 255, 255)
rgb(255, 255, 255)
rgb(255, 241, 237)
rgb(255, 220, 212)
;

$palette-accent-50: nth($palette-accent, 1);
$palette-accent-100: nth($palette-accent, 2);
$palette-accent-200: nth($palette-accent, 3);
$palette-accent-300: nth($palette-accent, 4);
$palette-accent-400: nth($palette-accent, 5);
$palette-accent-500: nth($palette-accent, 6);
$palette-accent-600: nth($palette-accent, 7);
$palette-accent-700: nth($palette-accent, 8);
$palette-accent-800: nth($palette-accent, 9);
$palette-accent-900: nth($palette-accent, 10);
$palette-accent-A100: nth($palette-accent, 11);
$palette-accent-A200: nth($palette-accent, 12);
$palette-accent-A400: nth($palette-accent, 13);
$palette-accent-A700: nth($palette-accent, 14);


![Screenshot_20201107_160229](https://user-images.githubusercontent.com/71029742/98444564-a7023600-2112-11eb-9a65-4a2bd73461bd.png)
