### ISSUE TITLE
Création des enums de données et utilisation dans le front.

### ISSUE THREAD

**Issue by Zephyrin** [Zephyrin/BraKoLu#3]
Supprimer les enums créer dans le front pour utiliser ceux provenant du back pour simplifier la vue.

**Comment by brakolu** [comment]
OK, voir la modif push sur celle existante car il me semble qu'il y avait erreur en la matière. 
Et si c'est bon ce que j'ai fait, pour la suite, c'est quoi le CLI pour généré tout ça ?

**Comment by Zephyrin** [comment]
@brakolu , Je n'ai pas vu tes modifications ;S 
Je l'ai fais de manière un peu générique pour les ingrédients et les enfants.

**Comment by Zephyrin** [comment]
Mise à jour avec le commit d'aujourd'hui des enums du stocks.
